#!/usr/bin/env bash

. /srv/lib/conf

load_conf $(basename $0) ssh_user_host

arena_comm=/srv/bin/run
sandbox_comm=/srv/bin/run-sandbox
gzip_header='\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\x03'
refresh_required='The TIO API was updated since this page was loaded. Please refresh for the lastest version.'

error()
{
	echo -en "Status: $1\n\n$2"
	rm -r $temp 2> /dev/null
	exit 1
}

cat << 'EOH'
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: TIO-Cache
Access-Control-Expose-Headers: TIO-Token
Content-Type: application/octet-stream
EOH

[[ $REQUEST_METHOD == POST ]] || error 405
if [[ $PATH_INFO =~ /api/ ]]; then
	echo 'Content-Encoding: gzip'
else
	[[ $PATH_INFO =~ /v65753536/ ]] || error 409 "$refresh_required"
fi

temp=$(mktemp -d /srv/tmp/XXX) || error 500
request=$temp/request
response=$temp/response
head -c 64K > $request
(( $(head -c 1 | wc -c) == 0 )) || error 413
cache=/srv/cache/$(sha512sum $request | cut -b 1-64)

if [[ $PATH_INFO =~ /no-cache/ ]] || ! ln $cache $response 2> /dev/null; then
	id_alnum=${temp: -3}
	id_numeric=$[62#$id_alnum]
	printf -v range s0-s0:c%u,c%u $[id_numeric & 511] $[id_numeric >> 9 | 512]
	token=$id_alnum/$(head -c 8 /dev/urandom | xxd -ps)
	echo "pid=$$;range=$range" > /srv/tmp/$token
	echo -en "TIO-Cache: miss\nTIO-Token: $token\n\n$gzip_header"
	{ echo -en "$gzip_header"; cat $request; } | zcat 2> /dev/null |
		ssh $ssh_user_host $arena_comm $range $sandbox_comm |
		gzip --best | tail -c +11 | tee $response
	ln -f $response $cache
else
	echo -en "TIO-Cache: hit\n\n$gzip_header"
	cat $response
fi

rm -r $temp
