#!/usr/bin/env bash

arena_exec=/srv/bin/run
gzip_header='\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\x03'
ssh_user_host=runner@arena.tryitonline.net

error()
{
	echo -en "Status: $1\n\n"
	rm -r $temp 2> /dev/null
	exit $[$1 % 60]
}

[[ $REQUEST_METHOD == POST ]] || error 405

cat << 'EOH'
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: TIO-Cache
Access-Control-Expose-Headers: TIO-Token
Content-Type: application/octet-stream
EOH

[[ $PATH_INFO =~ /api/ ]] && echo 'Content-Encoding: gzip'

temp=$(mktemp -d /srv/tmp/XXX) || error 500
request=$temp/request
response=$temp/response
head -c 64K > $request
(( $(head -c 1 | wc -c) == 0 )) || error 413
cache=/srv/cache/$(sha512sum $request | cut -b 1-64)

if [[ $PATH_INFO =~ /no-cache/ ]] || ! ln $cache $response 2> /dev/null; then
	id_alnum=${temp: -3}
	id_numeric=$[62#$id_alnum]
	printf -v range s0-s0:c%u,c%u $[id_numeric & 511] $[id_numeric >> 9 | 512]
	token=$id_alnum/$(head -c 8 /dev/urandom | xxd -ps)
	touch /srv/tmp/$token
	echo -en "TIO-Cache: miss\nTIO-Token: $token\n\n$gzip_header"
	{ echo -en "$gzip_header"; cat $request; } | zcat 2> /dev/null |
		ssh $ssh_user_host $arena_exec $range |
		gzip --best | tail -c +11 | tee $response
	ln -f $response $cache
else
	echo -en "TIO-Cache: hit\n\n$gzip_header"
	cat $response
fi

rm -r $temp
