#!/usr/bin/env bash

store=/srv/store

error()
{
	[[ -v uuid ]] && rm $uuid 2>&-
	echo -en "Status: $1\n\n"
	exit 1
}

[[ $REQUEST_METHOD == POST ]] || error 405
cd "$store" || error 500
uuid=$(mktemp XXXXX)
(( $? )) && error 500

head -c 64K >> $uuid
(( $(head -c 1 | wc -c) )) && error 413
gzip --best --no-name $uuid

echo -en "Access-Control-Allow-Origin: *\nContent-type: text/plain\n\n$uuid"
