#!/usr/bin/env bash

cd /tmp
mkdir -p MAlonzo/Code
cp -r /opt/agda/MAlonzo/Code/* MAlonzo/Code/
cp ~/.code.tio code.agda

agda -c -i /usr/share/Agda-stdlib/src "${TIO_CFLAGS[@]}" code.agda >&2
./code "$@" < ~/.input.tio
