#!/usr/bin/env bash

if [[ "$LD_PRELOAD" ]]; then
	unset LD_PRELOAD
	exec "$0" "$@"
fi

export DYALOG=${DYALOG:-$(ls -d /opt/mdyalog/*/64/unicode | tail -1)}
export FLAGS=${FLAGS--script}
export MAXWS=128M WSPATH=$DYALOG/ws

{
	echo :namespace
	cat .code.tio
	echo
	echo :endnamespace
} > ~/.bin.tio.dyalog

{
	echo "⎕PW←32767"
	echo "'#'⎕NS('FIX'⍎⍨⎕FIX'file:///opt/apl-dyalog-extended/FIX.dyalog')'file://$HOME/.bin.tio.dyalog'"
	cat .input.tio
	echo
} | $DYALOG/dyalog $FLAGS "$@"
