#!/usr/bin/env bash

export DYALOG=${DYALOG:-$(ls -d /opt/mdyalog/*/64/unicode | tail -1)}
export MAXWS=128M WSPATH=$DYALOG/ws

{
	echo :namespace
	cat .code.tio
	echo
	echo :endnamespace
} > ~/.bin.tio.dyalog

{
	echo "⎕PW←32767"
	echo "'#'⎕NS⎕FIX'file://$HOME/.bin.tio.dyalog'"
	cat .input.tio
	echo
} | $DYALOG/dyalog -script "$@"
