#!/usr/bin/env bash

export DYALOG=${DYALOG:-/opt/mdyalog/15.0/64/unicode}
export MAXWS=128M WSPATH=$DYALOG/ws

{
	echo :namespace TIO_$(head -c 16 /dev/urandom | xxd -ps)
	cat .code.tio
	echo
	echo "'#'⎕NS⎕NL-⍳9"
	echo "#.(⎕AVU⎕CT⎕DCT⎕DIV⎕FR⎕IO⎕LX⎕ML⎕PATH⎕PP⎕PW⎕RL⎕RTL⎕SM⎕TRAP⎕USING⎕WSID⎕WX)←⎕AVU⎕CT⎕DCT⎕DIV⎕FR⎕IO⎕LX⎕ML⎕PATH⎕PP⎕PW⎕RL⎕RTL⎕SM⎕TRAP⎕USING⎕WSID⎕WX"
	echo :endnamespace
} > ~/.bin.tio.dyalog

{
	echo "⎕PW←9999"
	echo "{}2⎕FIX'file://$HOME/.bin.tio.dyalog'"
	cat .input.tio
	echo
} | $DYALOG/dyalog -script "$@"
