#!/usr/bin/env bash

brachylog="/opt/Brachylog/prolog_parser/brachylog.pl"
echo -n "$1" > .tmp.tio
swipl -g "consult('$brachylog'),run_from_files_no_file('.code.tio','.input.tio','.tmp.tio')" -t halt
