#!/usr/bin/env bash

ln -fst . /opt/cs-csc/{Properties/,TIO.csproj,packages/,packages.json}
ln -f .code.tio Program.cs

msbuild /verbosity:quiet "${TIO_CFLAGS[@]}" >&2
mono bin/TIO.exe "$@" < .input.tio
