#!/usr/bin/env bash

export PATH="/opt/cyclone/bin:/opt/cyclone/local/bin:$PATH"
export LIBRARY_PATH="/opt/cyclone/lib:/opt/cyclone/lib/i486-linux-gnu/4.2:$LIBRARY_PATH"
export LD_LIBRARY_PATH="/opt/cyclone/lib2:$LD_LIBRARY_PATH"

ln -f .code.tio .code.tio.cyc
cyclone "${TIO_CFLAGS[@]}" -o .bin.tio .code.tio.cyc
./.bin.tio "$@" < .input.tio
