#!/usr/bin/env bash

cp -r /opt/microsoft/home/.dotnet .
ln -fst . /opt/microsoft/home/.{local,nuget}
mkdir -p project/obj
cd project
ln -fst . /opt/microsoft/home/fsharp/project.fsproj
ln -fst obj/ /opt/microsoft/home/fsharp/obj/*
ln -f ../.code.tio Program.fs
dotnet build "${TIO_CFLAGS[@]}" --no-restore >&2
cd ..
dotnet project/bin/*/netcoreapp*/project.dll "$@" < .input.tio
