#!/usr/bin/env bash

export HOME=/opt/microsoft/home
mkdir -p project/obj
cd project
ln -fst . /opt/microsoft/home/fsharp/project.csproj
ln -fst obj/ /opt/microsoft/home/fsharp/obj/*
ln -f ../.code.tio Program.fs
dotnet build >&2
cd ..
dotnet project/bin/Debug/netcoreapp*/project.dll "$@" < .input.tio
