#!/usr/bin/env bash

ln -fst . /opt/cs-csc/{Properties,TIO-FS.fsproj,packages/,packages.json}
ln -f .code.tio Program.fs

msbuild /verbosity:quiet "${TIO_CFLAGS[@]}" >&2
mono bin/TIO.exe "$@" < .input.tio
