#!/usr/bin/env bash

count()
{
	echo $#;
}

ln .code.tio Main.java
javac Main.java
shopt -s nullglob
if (($(count *.class) == 1)); then
	printf -v class %s *.class
	java "${class%.class}" "$@" < .input.tio
else
	java Main "$@" < .input.tio
fi
