#!/usr/bin/env bash

cat > wrapper.m <<- '.'
	$CharacterEncoding = "UTF-8"
	Get[".code.tio"]
.

export LD_LIBRARY_PATH=/opt/mathematica/fontconfig/usr/lib64:$LD_LIBRARY_PATH

/opt/mathematica/SystemFiles/Kernel/Binaries/Linux-x86-64/wolframscript -file wrapper.m "$@" < .input.tio
