#!/usr/bin/env bash

export HOME=/tmp/home
ln -fs "$(pwd)" $HOME
ln -fs /opt/microsoft/home/.local $HOME/
bom=$'\xef\xbb\xbf'
cat <(echo -n $bom) .code.tio > .code.tio.ps1
cat <(echo -n $bom) .input.tio > .input.tio.txt

if [[ $0 == *-core ]]; then
	> aliases.ps1
else
	sed 's/.*/Set-Alias & -Option AllScope -Scope Global/' > aliases.ps1 <<- .
		ac     Add-Content
		cat    Get-Content
		cp     Copy-Item
		cpp    Copy-ItemProperty
		date   Get-Date
		diff   Compare-Object
		ls     Get-ChildItem
		man    help
		mount  New-PSDrive
		mv     Move-Item
		ps     Get-Process
		random Get-Random
		rm     Remove-Item
		rmdir  Remove-Item
		sleep  Start-Sleep
		sort   Sort-Object
		tee    Tee-Object
		write  Write-Output
	.
fi

pwsh -Command "cd; ./aliases.ps1; Get-Content .input.tio.txt | ./.code.tio.ps1" "$@"
