#!/usr/bin/env bash

ln -fst . /opt/microsoft/home/{.{dotnet,local,nuget},qsharp/qsharp.csproj}
printf '%s\n' "${TIO_DRIVER[@]}" > Driver.cs
ln -f .code.tio Operation.qs

dotnet run "$@" < .input.tio
