#!/usr/bin/env bash

ln -fst . /opt/cs-csc/{Properties,TIO-VB.vbproj,packages/,packages.json}
ln -f .code.tio Application.vb

msbuild /verbosity:quiet "${TIO_CFLAGS[@]}" >&2
mono bin/TIO.exe "$@" < .input.tio
