#!/usr/bin/env bash

set -e

error()
{
	echo "$0: error: $1" >&2
	false
}

list()
{
	load_conf "$1" arena_pool
	IFS=$'\n'
	echo "${arena_pool[*]}"
	exit
}

pool_dir=/srv/etc/arena_pool.d
mkdir -p $pool_dir
(( $# )) || error "Missing action."
action="$1"
shift
source /srv/lib/conf

case "$action" in
	enabled|enabled-*)
		list run${action#enabled}
	;;
	list)
		list arena_pool
	;;
esac

(( $# )) || error "Missing argument to '$action'."
[[ $* =~ / ]] && error "Invalid character '/' in arguments."

case "$action" in
	add)
		mkdir -p $pool_dir
		cd $pool_dir
		tee -- "$@" <<< 'arena_pool+=("$(basename "$BASH_SOURCE")")' > /dev/null
	;;
	disable|disable-*)
		cd "$pool_dir/../run${action#disable}.d"
		\rm -f -- "$@"
	;;
	enable|enable-*)
		cd $pool_dir
		dir=../run${action#enable}.d
		mkdir -p "$dir"
		ln -frst "$dir" -- "$@"
	;;
	remove|rm)
		cd $pool_dir
		\rm -f -- "$@"
	;;
	*)
		error "The action '$action' is not implemented."
	;;
esac
