#!/usr/bin/env bash

((EUID == 0)) && exec sudo -E -u apache "$0" "$@"

gzip_header='\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\x03'

error()
{
	rm -f $temp
	(( $1 == 0 )) && exit 0
	echo -en "Status: $1\n\n$2"
	exit 1
}

echo 'Content-Type: application/octet-stream'

[[ $REQUEST_METHOD == POST ]] || error 405

read -n 64 hash
[[ "$hash" =~ ^[0-9a-f]{64}$ ]] || error 400

cache=/srv/cache/${hash:0:2}/${hash:2:62}
temp=$(mktemp /srv/tmp/XXX) || error 500

ln --force $cache $temp 2> /dev/null || error 204

if [[ $PATH_INFO =~ /api/ ]]; then
	echo 'Content-Encoding: gzip'
fi

echo -en "Status: 200\n\n$gzip_header"
cat $temp
error 0
