#!/usr/bin/env bash

error()
{
	echo -en "Status: $1\n\n"
	(( $1 < 300 ))
	exit
}

token=${PATH_INFO:1}

[[ $REQUEST_METHOD == GET ]] || error 405
[[ "$token" =~ ^[0-9a-f]{32}$ ]] || error 400
{
	temp=$(dirname $(find /srv/tmp -name $token)) && source $temp/meta-data || error 202
} 2> /dev/null
kill -USR1 $pid
ssh $ssh_user_host killall -Z $range -INT \; sleep 1 \; killall -Z $range -KILL
error 204
