#!/usr/bin/env bash

((EUID == 0)) && exec sudo -E -u apache "$0" "$@"

trap 'error 130' INT
trap 'error 143' TERM
trap 'do_not_cache=1' USR1

script_uuid=$(basename $0)
script_name=${script_uuid#*-}
arena_comm=/srv/bin/run
sandbox_comm=/srv/bin/run-sandbox
gzip_header='\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\x03'

error()
{
	rm -rf $temp
	(( $1 == 0 )) && exit 0
	kill $child_pid 2> /dev/null
	sleep 1
	[[ $range ]] && ssh $ssh_user_host killall -Z $range -KILL
	(( $1 < 200 )) && exit $1
	echo -en "Status: $1\n\n$2"
	exit 1
}

echo 'Content-Type: application/octet-stream'

[[ $REQUEST_METHOD == POST ]] || error 405

if [[ $PATH_INFO =~ /api/ ]]; then
	echo 'Content-Encoding: gzip'
fi

temp=$(mktemp -d /srv/tmp/XXX) || error 500
meta_data=$temp/meta-data
request=$temp/request
response=$temp/response
head -c 1MB > $request
(( $(head -c 1 | wc -c) == 0 )) || error 413
hash=$(sha256sum $request)
cache=/srv/cache/${hash:0:2}/${hash:2:62}
source /srv/lib/conf
load_conf $script_name arena_pool

ssh_user_host=($(
	shopt -s nullglob
	for arena in ${arena_pool[@]}; do
		echo -en "$arena\t"
		cat /srv/tmp/*/meta-data | grep --count "ssh_user_host=$arena"
	done | sort --random-sort | sort --key=2n --stable
))

load_conf $script_name ssh_user_host timeout_hard timeout_soft

id_alnum=${temp: -3}
id_numeric=$[62#$id_alnum]
printf -v range s0-s0:c%u,c%u $[id_numeric & 511] $[id_numeric >> 9 | 512]
token=${PATH_INFO##*/}
if [[ "$token" ]]; then
	[[ "$token" =~ ^[0-9a-f]{32}$ ]] || error 400
	touch $temp/$token
fi

cat > $meta_data << .
pid=$$
range=$range
ssh_user_host=$ssh_user_host
.

echo -en "Status: 200\n\n$gzip_header"

{
	echo -en "$gzip_header" \
		| cat - $request \
		| zcat 2> /dev/null \
		| ssh $ssh_user_host $arena_comm $range $sandbox_comm $timeout_hard $timeout_soft $REMOTE_ADDR \
		| gzip --best \
		| tail -c +11 \
		| tee $response
} &

child_pid=$!
wait $child_pid

(( do_not_cache )) || ln -f $response $cache

error 0
