#!/usr/bin/env bash

conf_dir=/srv/etc

load_conf()
{
	conf_file=$conf_dir/$1
	shift
	. "$conf_file"
	for name in "$@"; do
		if ! [[ ${!name} ]]; then
		echo "$0: error: Variable '$name' must be set in '$conf_file'." >&2
		exit 1
	fi
	done
}
