#!/usr/bin/env bash

conf_dir=/srv/etc

load_conf()
{
	conf_name=$1
	shift
	for conf_file in $conf_dir/$conf_name $conf_dir/$conf_name.d/*; do
		[[ -f "$conf_file" ]] && source "$conf_file" || true
	done
	for name in "$@"; do
		NAME=${name^^}
		if [[ ${!NAME} ]]; then
			declare -g "$name=${!NAME}"
		elif ! [[ ${!name} ]]; then
			echo "$0: error: Variable '$name' must be set in '$conf_dir/$conf_name' or '$conf_dir/$conf_name.d'." >&2
			exit 1
		fi
	done
}
