#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

error()
{
	echo "$0: error: $1" >&2
	false
}

tiosubst()
{
	if [[ $(file --brief --mime-type "$file") =~ ^text/ ]]; then
		envsubst "$(printf '$%s ' ${!tio_*})" < "$1"
	else
		cat "$1"
	fi
}

wordalize()
{
	printf -v $2 ${!1//[^0-9A-Za-z]/_}
}

source=/srv/usr/share/$1
destination=/srv/var/www/${2:-$1}
cd "$source"
mkdir --parents "$destination/static"
source /srv/lib/conf
unset ${!tio_*}
load_conf build tio_url
export ${!tio_*}
source /srv/lib/crypto
declare -A hashes
declare -l name

for file in *;do
	hash=$(tiosubst "$file" | tiohash 16 | hex)
	wordalize file name
	hashes[$name]=$hash
	export tio_$name=$hash-$file
done

for file in *; do
	wordalize file name
	uuid=$destination/static/${hashes[$name]}-$file
	tiosubst "$file" > "$uuid"
	ln --force --symbolic "$uuid" "$destination/$file"
done

restorecon -R "$destination"
