#!/usr/bin/env bash

declare -i "max_count=$1" || exit 1

while true; do
	ps -o label= -u runner | sort | uniq -c | while read count label; do
		if ((count > max_count)) && [[ $label =~ sandbox_t ]]; then
			while killall -Z $label -u runner; do
				sleep 0.1
			done
		fi
	done
	sleep 1
done
