#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o xtrace

if [[ "$1" == -n ]]; then
	no_reboot=1
	shift
else
	no_reboot=0
fi

for host in "$@"; do
	cat /srv/var/sync/exclude/* | \
		rsync --archive --delete --exclude-from=- --hard-links --sparse --xattrs / "$host:/"

	if ((no_reboot == 0)); then
		ssh "$host" init 6
		echo "Waiting for $host to reboot."

		while ! ping -c 1 "$host" &> /dev/null; do
			sleep 1
		done
	fi
done
