#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

if [[ "$1" == -n ]]; then
	no_reboot=1
	echo "Disabling automatic reboot."
	shift
else
	no_reboot=0
fi

for host in "$@"; do
	echo "Syncing $host."

	cat /srv/var/sync/exclude/* | \
		rsync --archive --delete --exclude-from=- --hard-links --sparse --xattrs / "$host:/"

	if ((no_reboot == 0)); then
		ssh "$host" init 6 || true
		echo "Waiting for $host to reboot."

		while ping -c 1 -w 1 "$host" &> /dev/null; do
			sleep 1
		done

		while ! ping -c 1 -w 1 "$host" &> /dev/null; do
			sleep 1
		done
	fi

	echo "Done."
done
