#!/bin/bash

bin="$(realpath "../bin/${HTTP_HOST/.*}")"

if ! [ -f "$bin" ]; then
	echo -e "Status: 404\n"
	exit
fi

echo -e "Content-type: application/octet-stream\n"

TEMP="$(mktemp -d)"

cd "$TEMP"

IFS="&" read -ra input

for field in "${input[@]}"; do
	while IFS="=" read -r name value; do
		if [[ $name =~ ^(code|input)$ ]]; then
			printf "%b" "${value//%/\\x}" > "$name"
		elif [[ $name = "args" ]]; then
			IFS="+" read -ra args_encoded <<< "$value"

			args=()

			for arg in "${args_encoded[@]}"; do
				args+=("$(printf "%b" "${arg//%/\\x}")")
			done
		elif [[ $name = "debug" ]]; then
			exec 2>&1
		fi
	done <<< "$field"
done

if [ -f input ]; then
  timeout 60s "$bin" code "${args[@]}" < input
else
  timeout 60s "$bin" code
fi

cd - >&-

rm -r "$TEMP"
