#!/bin/bash

bin="$(realpath "../bin/${HTTP_HOST/.*}")"

if ! [ -f "$bin" ]; then
	echo -e "Status: 404\n"
	exit
fi

uuid="$(head -c 16 /dev/urandom | xxd -ps)"
temp="/tmp/$uuid"

mkdir "$temp"

if ! cd "$temp"; then
	echo -e "Status: 500\n"
	exit
fi

echo $$ > pid

echo -e "Content-type: application/octet-stream\nAccess-Control-Allow-Origin: *\n\n$uuid"

IFS="&" read -ra input

for field in "${input[@]}"; do
	while IFS="=" read -r name value; do
		if [[ $name =~ ^(code|input)$ ]]; then
			printf "%b" "${value//%/\\x}" > "$name"
		elif [[ $name = "args" ]]; then
			IFS="+" read -ra args_encoded <<< "$value"

			args=()

			for arg in "${args_encoded[@]}"; do
				args+=("$(printf "%b" "${arg//%/\\x}")")
			done

			if [[ ${#args[@]} = 0 ]]; then
				args=""
			fi
		elif [[ $name = "debug" ]]; then
			exec 2>&1
		fi
	done <<< "$field"
done

time timeout 60s stdbuf -o0 -e0 "$bin" code "${args[@]}" < input

cd ..

rm -r "$temp"
