#!/bin/bash

conf="../conf/${HTTP_HOST/.*}"

if ! [ -f "$conf" ]; then
	echo -e "Status: 404 Not Found\n"
	exit
fi

source "$conf"

cat << EOF
Content-type: text/html

<!DOCTYPE html>
<html>
	<head>
		<title>$lang_name &ndash; Try it online!</title>
		<link rel="stylesheet" type="text/css" href="frontend.css" />
	</head>
	<body>
		<div id="wrapper">
			<h1>
				<a href="$lang_link">$lang_name</a>
				&ndash;
				<a href="//tryitonline.net/">Try it online!</a>
			</h1>

			<h2>Code</h2>
			<textarea id="code"></textarea>

			<h2>Input</h2>
			<textarea id="input"></textarea>

			<h2>Arguments</h2>
			<div id="args">
				<div id="arg-placeholder">
					<a onclick="addCLA()">+</a>
				</div>
			</div>

			<div>
				<input type="button" id="run" value="Run" onclick="run()">
				<input type="button" value="Permalink" onclick="permalink()">
				<input type="button" id="debug" value="Debug" class="off" onclick="toggle(this)">
			</div>

			<h2>Output</h2>
			<textarea id="output" disabled></textarea>
		</div>

		<script src="frontend.js"></script>
	</body>
</html>
EOF
