#!/bin/bash

conf="../conf/${HTTP_HOST/.*}"

if ! [ -f "$conf" ]; then
	exec ./index
fi

source "$conf"

cat << EOF
Content-type: text/html
Access-Control-Allow-Origin: *

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>$lang_name &ndash; Try it online!</title>
		<link rel="stylesheet" type="text/css" href="frontend.css" />
	</head>
	<body>
		<nav>
			<a href="//tryitonline.net/" id="home">Try it online!</a>
			<a href="$lang_link" id="lang" title="$lang_name homepage">$lang_name</a>
				<a class="button" id="run" onclick="run()" title="Execute the program. (Alt-R/Ctrl-Enter)">&#x2699; Run</a>
				<a class="button" onclick="permalink()" title="Generate a permalink. (Alt-S)">&#x270d; Save</a>
				<a class="button off" id="debug" onclick="toggleDebug()" title="Display or hide STDERR." value="&#x2714; Debug;">&#x2718; Debug</a>
				<a class="button" href="//tryitonline.net/donate/" target="_blank" title="Make a donation">&#x1f4b0; Donate</a>
		</nav>
		<div id="wrapper">
			<h2>
				<a class="icon"></a>
				Code
				<span id=char-count></span>
			</h2>

			<div class="section-body">
				<a class="icon"></a>
				<textarea id="code" autofocus autocapitalize="off" spellcheck="false"></textarea>
			</div>

			<h2>
				<a class="icon" id="inputToggle" onclick="toggleInput()" title="Display or hide the input field.">&#x270e;</a>
				Input
			</h2>

			<div class="section-body">
				<a class="icon"></a>
				<textarea id="input" autocapitalize="off" spellcheck="false"></textarea>
			</div>

			<h2>
				<a class="icon" onclick="addCLA()" title="Add a command-line argument.">&#x2795;</a>
				Arguments
			</h2>

			<div class="section-body" id="args"></div>

			<h2>
				<a class="icon"></a>
				Output
			</h2>

			<div class="section-body">
				<a class="icon"></a>
				<textarea id="output" readonly></textarea>
			</div>
		</div>

		<script src="frontend.js"></script>
	</body>
</html>
EOF
