#!/usr/bin/env bash

((EUID == 0)) && exec sudo -E -u apache "$0" "$@"

trap 'do_not_cache=1' USR1
script_name=$(basename $0)
arena_comm=/srv/bin/run
sandbox_comm=/srv/bin/run-sandbox
gzip_header='\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\x03'
refresh_required='The TIO API was updated since this page was loaded. Please refresh for the lastest version.'

error()
{
	rm -rf $temp
	(( $1 )) || exit 0
	echo -en "Status: $1\n\n$2"
	exit 1
}

cat << '.'
Access-Control-Expose-Headers: TIO-Cache
Access-Control-Expose-Headers: TIO-Token
Content-Type: application/octet-stream
.

[[ $REQUEST_METHOD == POST ]] || error 405
if [[ $PATH_INFO =~ /api/ ]]; then
	echo 'Content-Encoding: gzip'
else
	[[ $PATH_INFO =~ /v6584f539/ ]] || error 409 "$refresh_required"
fi

temp=$(mktemp -d /srv/tmp/XXX) || error 500
meta_data=$temp/meta-data
request=$temp/request
response=$temp/response
head -c 64K > $request
(( $(head -c 1 | wc -c) == 0 )) || error 413
hash=$(sha512sum $request)
cache=/srv/cache/${hash:0:2}/${hash:2:62}
source /srv/lib/conf
load_conf $script_name arena_pool

ssh_user_host=($(
	shopt -s nullglob
	for arena in ${arena_pool[@]}; do
		echo -en "$arena\t"
		cat /srv/tmp/*/meta-data | grep --count "ssh_user_host=$arena"
	done | sort --random-sort | sort --key=2n --stable
))

load_conf $script_name ssh_user_host timeout_hard timeout_soft

if ! [[ $PATH_INFO =~ /no-cache/ ]] && ln $cache $response 2> /dev/null; then
	echo -en "TIO-Cache: hit\n\n$gzip_header"
	cat $response
	error 0
fi

id_alnum=${temp: -3}
id_numeric=$[62#$id_alnum]
printf -v range s0-s0:c%u,c%u $[id_numeric & 511] $[id_numeric >> 9 | 512]
token=$id_alnum/$(head -c 8 /dev/urandom | xxd -ps)
touch /srv/tmp/$token

cat > $meta_data << .
pid=$$
range=$range
ssh_user_host=$ssh_user_host
.

echo -en "TIO-Cache: miss\nTIO-Token: $token\n\n$gzip_header"

cat <(echo -en "$gzip_header") $request \
	| zcat 2> /dev/null \
	| ssh $ssh_user_host $arena_comm $range $sandbox_comm $timeout_hard $timeout_soft \
	| gzip --best \
	| tail -c +11 \
	| tee $response

(( do_not_cache )) || ln -f $response $cache

error 0
